### PR TITLE
Fix SASS parent selector usage

### PR DESCRIPTION
**Pull request by BadCoder1337**
Fix for #22 
Parent selector only allowed at the beginning of compound selectors
https://sass-lang.com/documentation/style-rules/parent-selector

### CODE REVIEW

**Comment by vivisrc** [comment]
It's supported in styled-components, which doesn't use sass but it's own interpreter

**Comment by BadCoder1337** [comment]
I think it's styled-components bug, different styles with same name definitely not intentional
image

**Comment by BadCoder1337** [comment]
Demo [here](https://discohook-pr.rainbow6.ru/?data=eyJtZXNzYWdlcyI6W3siZGF0YSI6eyJjb250ZW50IjpudWxsLCJlbWJlZHMiOlt7ImRlc2NyaXB0aW9uIjoiYHRlc3RgIiwiY29sb3IiOjU4MTQ3ODN9XX19XX0)

**Comment by vivisrc** [comment]
I think it's best to look around for other ways to do this, the `RichEmbedContainer` shouldn't declare how `Code` looks, instead `Code` should react to being inside of a `RichEmbedContainer`.

This also happens to any other component that is styled with `+ &`, and fixing some of those is impractical. I think it's best to look for a different solution.

**Comment by vivisrc** [comment]
Checked locally and this solution does seem to work properly, could you do it for the other files too?
```
./common/input/checkable/layout/CheckableButton.ts:  input:hover + & {
./common/input/checkable/layout/CheckableButton.ts:  input:focus + & {
./common/input/checkable/layout/CheckableButton.ts:  input:disabled + & {
./modules/markdown/styles/CodeBlockContainer.ts:  ${RichEmbedContainer} & {
./common/input/file/FileInputField.tsx:  input:focus + & {
./common/input/file/PasteFileButton.tsx:  input:focus + & {
```

**Review by vivisrc — APPROVED** [review]
LGTM

**Pull request merged**
